baseURL = 'https://kjhaber.github.io/'
languageCode = 'en-us'
title = "Keith's Notes"
copyright = "Keith Haber"
theme = 'archie'

[params]
  customcss = ["css/style.css"]
  favicon = "favicon-32x32.png"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
